import type { SpriteData } from './types'
import { Direction } from './types'

/**
 * A complete character sprite set extracted from a MetroCity character PNG.
 *
 * Each character PNG is 112x96:
 *   - 3 direction rows (down=0-31, up=32-63, right=64-95), each 32px tall
 *   - 7 frame columns, each 16px wide
 *   - Frames: walk0(0), walk1(1), walk2(2), type0(3), type1(4), read0(5), read1(6)
 *
 * Left direction sprites are generated by flipping the right sprites horizontally.
 */
export interface CharacterSpriteSet {
	walk: Record<Direction, SpriteData[]>
	typing: Record<Direction, SpriteData[]>
}

const NUM_CHARACTERS = 6
const PNG_WIDTH = 224
const PNG_HEIGHT = 96
const FRAME_W = 32
const FRAME_H = 32

const CHARACTER_BASE_PATH = '/assets/office/characters'

const characterSets: (CharacterSpriteSet | null)[] = new Array(NUM_CHARACTERS).fill(null)
let loaded = false

/** Extract a single frame from canvas image data. */
function extractFrame(
	imageData: ImageData,
	frameCol: number,
	dirRow: number
): SpriteData {
	const sprite: SpriteData = []
	const startX = frameCol * FRAME_W
	const startY = dirRow * FRAME_H

	for (let y = 0; y < FRAME_H; y++) {
		const row: string[] = []
		for (let x = 0; x < FRAME_W; x++) {
			const px = startX + x
			const py = startY + y
			const idx = (py * PNG_WIDTH + px) * 4
			const r = imageData.data[idx] ?? 0
			const g = imageData.data[idx + 1] ?? 0
			const b = imageData.data[idx + 2] ?? 0
			const a = imageData.data[idx + 3] ?? 0

			if (a < 128) {
				row.push('')
			} else {
				const hex = '#'
					+ r.toString(16).padStart(2, '0')
					+ g.toString(16).padStart(2, '0')
					+ b.toString(16).padStart(2, '0')
				row.push(hex)
			}
		}
		sprite.push(row)
	}
	return sprite
}

/** Flip a sprite horizontally. */
function flipHorizontal(sprite: SpriteData): SpriteData {
	return sprite.map(row => [...row].reverse())
}

/** Load a single character PNG and extract all sprite sets. */
function loadCharacterPNG(index: number): Promise<CharacterSpriteSet> {
	return new Promise((resolve, reject) => {
		const img = new Image()
		img.crossOrigin = 'anonymous'
		img.onload = () => {
			const canvas = document.createElement('canvas')
			canvas.width = PNG_WIDTH
			canvas.height = PNG_HEIGHT
			const ctx = canvas.getContext('2d')
			if (!ctx) {
				reject(new Error('Failed to get canvas 2d context'))
				return
			}

			ctx.drawImage(img, 0, 0)
			const imageData = ctx.getImageData(0, 0, PNG_WIDTH, PNG_HEIGHT)

			// Direction rows in the PNG: down=0, up=1, right=2
			const DIR_ROW_DOWN = 0
			const DIR_ROW_UP = 1
			const DIR_ROW_RIGHT = 2

			// Extract individual frames per direction
			// Walk frames: 0, 1, 2 -> cycle as [0, 1, 2, 1]
			const walkDown = [0, 1, 2].map(f => extractFrame(imageData, f, DIR_ROW_DOWN))
			const walkUp = [0, 1, 2].map(f => extractFrame(imageData, f, DIR_ROW_UP))
			const walkRight = [0, 1, 2].map(f => extractFrame(imageData, f, DIR_ROW_RIGHT))

			// Type frames: 3, 4
			const typeDown = [3, 4].map(f => extractFrame(imageData, f, DIR_ROW_DOWN))
			const typeUp = [3, 4].map(f => extractFrame(imageData, f, DIR_ROW_UP))
			const typeRight = [3, 4].map(f => extractFrame(imageData, f, DIR_ROW_RIGHT))

			// Left = horizontal flip of right
			const walkLeft = walkRight.map(flipHorizontal)
			const typeLeft = typeRight.map(flipHorizontal)

			// Walk cycle: [0, 1, 2, 1]
			const walkCycle = (frames: SpriteData[]): SpriteData[] => [frames[0]!, frames[1]!, frames[2]!, frames[1]!]

			const set: CharacterSpriteSet = {
				walk: {
					[Direction.DOWN]: walkCycle(walkDown),
					[Direction.UP]: walkCycle(walkUp),
					[Direction.LEFT]: walkCycle(walkLeft),
					[Direction.RIGHT]: walkCycle(walkRight)
				},
				typing: {
					[Direction.DOWN]: typeDown,
					[Direction.UP]: typeUp,
					[Direction.LEFT]: typeLeft,
					[Direction.RIGHT]: typeRight
				}
			}

			resolve(set)
		}
		img.onerror = () => {
			reject(new Error(`Failed to load character PNG: char_${index}.png`))
		}
		img.src = `${CHARACTER_BASE_PATH}/char_${index}.png`
	})
}

/**
 * Load all 6 character PNGs. Call once at startup.
 * Silently handles missing PNGs (characters without sprites will return null).
 */
export async function loadAllCharacters(): Promise<void> {
	if (loaded) return

	const promises = Array.from({ length: NUM_CHARACTERS }, (_, i) =>
		loadCharacterPNG(i)
			.then((set) => {
				characterSets[i] = set
			})
			.catch((err) => {
				console.warn(`[office] Could not load char_${i}.png:`, err.message)
			})
	)

	await Promise.all(promises)
	loaded = true
}

/** Get the sprite set for a character palette (0-5), or null if not loaded. */
export function getCharacterSpriteSet(palette: number): CharacterSpriteSet | null {
	if (palette < 0 || palette >= NUM_CHARACTERS) return null
	return characterSets[palette] ?? null
}

/** Check if at least one character sprite has been loaded. */
export function hasCharacterSprites(): boolean {
	return characterSets.some(s => s !== null)
}
